### PR TITLE
fix for iOS 10

### PR DESCRIPTION
**Pull request by Watson1978**
1) fix comparing the version
The string comparing does not work as you expected.
```
irb(main):001:0> "9.3" >= "6"
=> true
irb(main):002:0> "10" >= "6"
=> false
```

2) add app.info_plist['NSContactsUsageDescription'] for authorization

### CODE REVIEW

**Comment by markrickert** [comment]
Looks good to me. @alexrothenberg can you merge, bump, and release a new version?

**Comment by alexrothenberg** [comment]
Done.  Released as https://rubygems.org/gems/motion-addressbook/versions/1.7.4

Sadly I'm not doing any rubymotion work now and my new laptop isn't setup with RubyMotion.  I've added both of you (@Watson1978 & @markrickert) with the commit bit to this repo. And I added @Watson1978 as an owner in rubygems (I couldn't get it to work with the email on @markrickert's github profile - but would be happy to add you too if there's another email that works).

Please feel free to do what you think is right without me in the future. I'm still happy to click the github and rubygems buttons but am not adding any value since I can't run the code.

**Comment by Watson1978** [comment]
Could you please merge this pull request for iOS 10 ?

**Comment by Watson1978** [comment]
@alexrothenberg thank you for adding me in owners :)

**Comment by alexrothenberg** [comment]
oops did I bump and release without merging.  :embarrassed:

Thanks for cleaning that up!

**Pull request merged**
